export enum Auth_ActionType {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  REGISTER_FAILURE = 'REGISTER_FAILURE',
  UPDATE_CURRENT = 'UPDATE_CURRENT',
  LOGOUT = 'LOGOUT',
  AUTH_LOADING = 'AUTH_LOADING',
}

export enum Posts_ActionType {
  GET_POSTS_REQUEST = 'GET_POSTS_REQUEST',
  GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE = 'GET_POSTS_FAILURE',
  POST_CREATED = 'POST_CREATED',
  POST_UPDATE = 'POST_UPDATE',
}
