export enum Auth_ActionType {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  REGISTER_FAILURE = 'REGISTER_FAILURE',
  UPDATE_CURRENT = 'UPDATE_CURRENT',
  LOGOUT = 'LOGOUT',
}
